version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=?
      - POSTGRES_USER=?
      - POSTGRES_PASSWORD=?
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=?
      - PGADMIN_DEFAULT_PASSWORD=?
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=?
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=?
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=?
      - PMA_HOST=mysql
    ports:
      - 8080:80
